# ./lib/pre-commit-config.full.yaml
# now includes all the jupyter and python checks
# if you want to exclude then use the exclude and put the directories in
#
# For the main source repo with random stuff in it
# tried dockerfilelint but too strict and disabling does not work
# cannot run check-builtin-literals due to foreign python code

# note that we exclude node_modules and _vendor for hugo
# since these are typically third party modules
# cannot run  markdownlint checks for hugo
---
# need this so gitlint only runs during commit-msg
default_stages: [commit, push]
# python regex https://www.programiz.com/python-programming/regex
exclude: (^archive/|^user/|deprecated/)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    # only language independent hooks
    rev: v4.3.0
    hooks:
      # allow up to 2MB files for jupyter notebooks
      - id: check-added-large-files
        args: ["--maxkb=2048"]
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      # exclude third-party files
      # https://github.com/psf/black/issues/395
      # do not run this since we do include.sh from elsewhere
      # - id: check-symlinks
      - id: check-toml
      - id: check-json
        exclude: (^_vendor/|^node_modules/)
      - id: pretty-format-json
        args: [--autofix]
        exclude: (^_vendor/|^node_modules/)
      - id: check-xml
        exclude: (^_vendor/|^node_modules/)
      # use yamllint instead as that is what neovim uses
      # - id: check-yaml
      #  args: [--allow-multiple-documents]
      #  exclude: (^_vendor/|^node_modules/)
      # https://github.com/pre-commit/pre-commit-hooks/blob/master/pre_commit_hooks/detect_aws_credentials.py
      - id: detect-aws-credentials
        args: [--allow-missing-credentials]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: forbid-new-submodules
      - id: mixed-line-ending
      # we allow direct commits to main uncomment if you PRs only
      # - id: no-commit-to-branch
      - id: trailing-whitespace
      - id: check-executables-have-shebangs
      - id: destroyed-symlinks
      # include.sh and surround.sh
      - id: check-symlinks
        exclude: (include.sh$|surround.sh$)
      # https://github.com/pre-commit/pre-commit-hooks/blob/master/pre_commit_hooks/detect_aws_credentials.py
      - id: name-tests-test
      - id: requirements-txt-fixer
      # python checking use pre-commit-config.python.yaml instead
      # - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first

  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      # dependent on local shellcheck install but must faster than docker
      - id: shellcheck
        args: [-x]
        exclude: (.*\.zsh$|\.zshrc$|\.zprofile$|\.fzf\.bash$|\.bashrc$|\.bash_profile$)
      # Generating a ruby error with run with all-files
      # this is using the ruby mdl utility so switching to the node version
      # because it has per line disabling of checks
      # - id: markdownlint
      # this requires a local shfmt but act does not handle snap install
      # properly so use the pre-commit that does its own install
      # - id: shfmt
      # https://github.com/jumanjihouse/pre-commit-hooks/issues/82
      # additional dependency bug in pre-commit v2.10
      # should be fixed now when doing a pre-commit all
      # additional_dependencies: []

  # this hook requires docker to get shellcheck so only use shellcheck not installed
  #- repo: https://github.com/koalaman/shellcheck-precommit
  #  rev: v0.8.0
  #  hooks:
  #    - id: shellcheck
  #      args: [-x]
  #      exclude: (.*\.zsh$|\.zshrc$|\.zprofile$|\.fzf\.bash$|\.bashrc$|\.bash_profile$)

  # this is bettert han the jumanji version as it uses go to build
  - repo: https://github.com/scop/pre-commit-shfmt
    rev: v3.5.1-1
    hooks:
      - id: shfmt
        exclude: (.*\.zsh$|\.zprofile|\.zshrc)

  # https://github.com/igorshubovych/markdownlint-cli
  # node version of markdownlint with better disabling of checks by line
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.2
    hooks:
      - id: markdownlint

  # https://jorisroovers.com/gitlint/#using-gitlint-through-pre-commit
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.18.0
    hooks:
      - id: gitlint
        stages: [commit-msg]

  # https://yamllint.readthedocs.io/en/stable/integration.html#integration-with-pre-commit
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.28.0
    hooks:
      - id: yamllint
        # use relaxed because .pre-commit-config has truthy value warning
        args: [-d relaxed]

  # python regex syntax for inclusion
  # https://www.w3schools.com/python/python_regex.asp
  # So this means only look at python files
  # files: ".py$"
  # This is only for python and other files
  # This means exclude directories ./typescript
  # exclude: "typescript|golang"

  # https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/
  # https://github.com/pre-commit/mirrors-mypy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.991'
    hooks:
      - id: mypy
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle
        exclude: thefuck/settings\.py$

  # puts the isort.cfg at the root we do not want that
  # https://pypi.org/project/seed-isort-config/
  # - repo: https://github.com/asottile/seed-isort-config
  #   rev: v2.2.0
  #   hooks:
  #     # remember this will place things at the root of the repo
  #     # but running in lint locally places it in the current directory
  #    - id: seed-isort-config
  # does not respect the local arguments
  # - repo: https://github.com/timothycrosley/isort
  #   rev: 5.2.0
  #   hooks:
  #     - id: isort
  #       args: [--profile=black, -w 79]
  # https://ljvmiranda921.github.io/notebook/2018/06/21/precommits-using-black-and-flake8/
  # switch to released black
  # #rev: 20.8b1

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.11
        args: [-l 79]

  # https://jupytext.readthedocs.io/en/latest/using-pre-commit.html
  # sync all notebooks with their corresponding markdown files
  # use black to format the python code
  - repo: https://github.com/mwouts/jupytext
    rev: v1.14.7
    hooks:
      - id: jupytext
        args: [--sync, --pipe, black]
        additional_dependencies:
          - black==23.3.0

  # strips everything out so use pre-commit-jupyter instead
  # - repo: https://github.com/kynan/nbstripout
  #  rev: 0.4.0
  #  hooks:
  #    - id: nbstripout

  # https://github.com/roy-ht/pre-commit-jupyter
  - repo: https://github.com/aflc/pre-commit-jupyter
    rev: v1.2.1
    hooks:
      - id: jupyter-notebook-cleanup
        args:
          - --remove-kernel-metadata
          - --pin-patterns
          - "[pin];[donotremove]"
        files: \.ipynb$
        types: ["file"]

  # strips everything out so use pre-commit-jupyter instead
  # - repo: https://github.com/kynan/nbstripout
  #   rev: 0.4.0
  #   hooks:
  #     - id: nbstripout

  # lint Dockerfiles with hadolint
  - repo: https://github.com/hadolint/hadolint
    rev: v2.12.1-beta
    hooks:
      # use if hadolint is local
      #- id: hadolint
      # using docker container because necktos act will not homebrew install
      - id: hadolint-docker
        exclude: Dockerfile.dockerignore
